version: 0.0
os: linux
files:
  - source: /
    destination: /opt/codedeploy-agent/deployment-root/1ff3b535-1fff-47e2-9225-a912b0bfe36a/d-DMRSWNSFJ/deployment-archive/
hooks:
  ApplicationStop:
    - location: Scripts/application_stop.sh
      timeout: 300
      runas: ec2-user
  BeforeInstall:
    - location: Scripts/before_install.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: Scripts/application_start.sh
      timeout: 300
      runas: ec2-user
